INSERT INTO USERS(NAME, EMAIL, PASSWORD) VALUES('Admin', 'adm@gmail.com', '$2y$10$yFMawZYOEH96JhgFxi1SQ.4zY.Y0CHybszilFGuhmm8uf6mHI0W/C');

INSERT INTO USER_ROLE(id, NAME) VALUES(1, 'ROLE_ADMIN');
INSERT INTO USER_ROLE(id, NAME) VALUES(2, 'ROLE_TEACHER');

INSERT INTO USERS_USER_ROLES(USER_MODEL_ID, USER_ROLES_ID) VALUES(1, 1);